# Site settings
title: Tshepang Mogaila
twitter_username: maestro_tshepang
name: Tshepang Mogaila

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/teeldinho
 - title: LinkedIn
   url: https://www.linkedin.com/in/mr-tshepang-mogaila

#Any buzzword skills you want to include
skills:
 - JQuery
 - CSS
 - Java
 - C++
 - SQL
 - REST
 - HTML
 - Javascript
 - Pascal

#Work experience is required
roles:
 - title: Teaching Assistant
   start: 2018
   end: 2018
   employer: UP
   description: Programming teaching assistant, involved in practicals tutoring.
 - title: Computer Trainer
   start: 2018
   end: 2018
   employer: UP
   description: Computer training lecturer.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2017
   subject: Computer Science
   school: University of Pretoria

intro: |
  I am a motivated young adult with exceptional leadership skills and an above average work-ethic. Passionate about learning new things and no stranger to exploring the unknown.